// ISO 3166 codes for hover-card flag thumbnails
export const FLAG_CODE_BY_TITLE = {
  Argentina: 'ar',
  Australia: 'au',
  Algeria: 'dz',
  Austria: 'at',
  Belgium: 'be',
  'Bosnia-Herzegovina': 'ba',
  Brazil: 'br',
  Cameroon: 'cm',
  Canada: 'ca',
  'Cape Verde': 'cv',
  Colombia: 'co',
  Croatia: 'hr',
  Curacao: 'cw',
  'Czech Republic': 'cz',
  'DR Congo': 'cd',
  Ecuador: 'ec',
  Egypt: 'eg',
  England: 'gb-eng',
  France: 'fr',
  Germany: 'de',
  Ghana: 'gh',
  Haiti: 'ht',
  'Ivory Coast': 'ci',
  Iran: 'ir',
  Iraq: 'iq',
  Japan: 'jp',
  Jordan: 'jo',
  'South Korea': 'kr',
  Mexico: 'mx',
  Morocco: 'ma',
  Netherlands: 'nl',
  'New Zealand': 'nz',
  Norway: 'no',
  Panama: 'pa',
  Paraguay: 'py',
  Portugal: 'pt',
  Qatar: 'qa',
  'Saudi Arabia': 'sa',
  Scotland: 'gb-sct',
  Senegal: 'sn',
  'South Africa': 'za',
  Spain: 'es',
  Sweden: 'se',
  Switzerland: 'ch',
  Tunisia: 'tn',
  Turkey: 'tr',
  USA: 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
};

export function getCountryFlagUrl(countryTitle, size = 80) {
  const code = FLAG_CODE_BY_TITLE[countryTitle];
  if (!code) return null;
  return `https://flagcdn.com/w${size}/${code}.png`;
}
